services:
  agent:
    volumes:
      - "/cephfs/home/ignatov/artifacts:/output"
      - ".:/dp-agent"
    ports:
      - ${AGENT_PORT}:4242
  kbqa:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=5
  factoid-classification:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=5
  text-qa:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=5
  comet-atomic:
    environment:
      - CUDA_VISIBLE_DEVICES=5
  comet-conceptnet:
    environment:
      - CUDA_VISIBLE_DEVICES=5
  knowledge-grounding:
    environment:
      - CUDA_VISIBLE_DEVICES=6
  midas-classification:
    environment:
      - CUDA_VISIBLE_DEVICES=6
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  combined-classification:
    environment:
      - CUDA_VISIBLE_DEVICES=7
  mongo:
    command: mongod
    image: mongo:4.0.0
    # # you can use persistent local volume if you need
    # volumes:
    #   - ./venv/data/db_data:/root/data/db
  cobotqa:
#  cobot-convers-evaluator-annotator:
#    volumes:
#      - "~/.deeppavlov:/root/.deeppavlov"
  cobot-nounphrases:
  program-y:
  personality-catcher:
  sentseg:
  convers-evaluation-selector:
  sentrewrite:
  intent-responder:
  intent-catcher:
  blacklisted-words:
  program-y-dangerous:
  dff-movie-skill:
  dff-gaming-skill:
  ner:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=7
  eliza:
  convert-reddit:
  personal-info-skill:
  asr:
  misheard-asr:
  book-skill:
  weather-skill:
  emotion-skill:
  dummy-skill-dialog:
  meta-script-skill:
  short-story-skill:
  coronavirus-skill:
  small-talk-skill:
  game-cooperative-skill:
  program-y-wide:
  news-api-skill:
  news-api-annotator:
  factoid-qa:
  entity-linking:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  wiki-parser:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  spelling-preprocessing:
  grounding-skill:
  masked-lm:
    environment:
      - CUDA_VISIBLE_DEVICES=8
  dff-friendship-skill:
  entity-storer:
  knowledge-grounding-skill:
  dff-animals-skill:
  dff-travel-skill:
  dff-sport-skill:
  dff-food-skill:
  dff-science-skill:
  dff-music-skill:
  fact-random:
  fact-retrieval:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=8
  dff-bot-persona-skill:
  dff-funfact-skill:
  dff-gossip-skill:
  hypothesis-scorer:
    environment:
      - CUDA_VISIBLE_DEVICES=8
  dff-wiki-skill:
  topic-recommendation:
  user-persona-extractor:
  wiki-facts:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
  dff-art-skill:
  entity-detection:
    volumes:
      - "~/.deeppavlov:/root/.deeppavlov"
    environment:
      - CUDA_VISIBLE_DEVICES=9
version: '3.7'
