version: "3.7"
services:
  neo4j:
    image: neo4j:4.2.5
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ~/neo4j/data:/data
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_connector_http_advertised__address: "0.0.0.0:7474"
      NEO4J_dbms_connector_bolt_advertised__address: "0.0.0.0:7687"
      NEO4J_dbms_connector_https_advertised__address: "0.0.0.0:7473"
  client:
    build:
      context: .
  fill_db:
    build:
      context: .
  server_neo4j:
    build:
      context: .
