apiVersion: v1
kind: Service
metadata:
  name: {{KUBER_LB_NAME}}
  namespace: {{ NAMESPACE }}
  annotations:
    prometheus.io/scrape: 'true'
    #service.beta.kubernetes.io/aws-load-balancer-type: nlb
    #service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: {{KUBER_DP_NAME}}
  {% if KUBER_DP_NAME != "agent-dp" %}
  type: ClusterIP
  {% else %}
  type: LoadBalancer
  {% endif %}
  ports:
  - name: lb-service
    protocol: TCP
    port: {{CLUSTER_PORT}}
    targetPort: dp-service

{% if KUBER_DP_NAME != "agent-dp" %}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{KUBER_LB_NAME}}-ingress
  namespace: {{ NAMESPACE }}
  annotations:
    # use nginx-ingress (needed if 2+ ingress controllers)
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /{{KUBER_LB_NAME}}/(.*)$
        backend:
          serviceName: {{KUBER_LB_NAME}}
          servicePort: {{CLUSTER_PORT}}
{% endif %}
