apiVersion: v1
kind: Namespace
metadata:
  name: alexa
---
apiVersion: v1
kind: Namespace
metadata:
  name: alexa-a
---
apiVersion: v1
kind: Namespace
metadata:
  name: alexa-b
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
